# Generated by Django 4.1 on 2022-08-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_vote_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='describtion',
            new_name='description',
        ),
    ]
